message("Building AppCommonLib")

# C++11 support
versionAtMost(QT_VERSION, 5.15.2){
    CONFIG += c++11
}

versionAtLeast(QT_VERSION, 6.0.0)){
    CONFIG += c++17
}

unix:!android{
    INCLUDEPATH += $${UI_DIR}
    INCLUDEPATH += $${MOC_DIR}
    message( linx generated include paths $${INCLUDEPATH})
}

INCLUDEPATH += $$PWD/AppsSrc/GoTvCommon/QtSource
INCLUDEPATH += $$PWD/AppsSrc
INCLUDEPATH += $$PWD/kodi_src/xbmc/xbmc
INCLUDEPATH += $$PWD/DependLibs/ffmpeg
INCLUDEPATH += $$PWD/GoTvCore

HEADERS += $$PWD/AppsSrc/GoTvCommon/QtSource/AccountDb.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AccountMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AcceptCancelWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityAppSetup.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityAddRemoveLibraryFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityBrowseFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityChooseTestWebsiteUrl.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityCreateAccount.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityDownloadItemMenu.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityFileSearch.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityInformation.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityIsPortOpenTest.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityMessageBox.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityNetworkState.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityPermissions.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanPeopleSearch.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanProfiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanStoryBoards.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanWebCams.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivitySessionOptions.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityShowHelp.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivitySoundOptions.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityStoryBoard.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityTimedMessage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityViewLibraryFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityViewMySharedFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityYesNoMsgBox.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppDefs.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppCommon.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppGlobals.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppProfile.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppSettings.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppSetup.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletAboutApp.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletApplicationInfo.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletAssetPlayerBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletBase.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletBrowseFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletCamClipPlayer.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletCamSettings.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletCamTest.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChatRoomJoin.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChatRoomClient.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChatRoomJoinSearch.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChooseThumbnail.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientAvatarImage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientRandomConnect.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientShareFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientShareWebCam.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientStoryboard.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletDownloads.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletEditAboutMe.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletEditAvatarImage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletEditStoryboard.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletFriendListClient.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGalleryImage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGalleryEmoticon.h \  
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGalleryThumb.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGetStarted.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupJoinSearch.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupJoin.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupListClient.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupListLocalView.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHelpNetSignalBars.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostGroupStatus.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostJoinRequestList.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostNetworkStatus.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostSelect.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletInviteAccept.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletInviteCreate.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletJoinGroupStatus.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletJoinBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletKodi.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLaunchPage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLaunchWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLibrary.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletLog.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLogSettings.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLogView.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletMultiMessenger.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletNetHostingPage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletNetworkSettings.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletPersonOfferList.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerChangeFriendship.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerReplyFileOffer.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerSelectFileToSend.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerSessionFileOffer.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerTodGame.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerVideoPhone.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerViewSharedFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerVoicePhone.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPermissionList.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPersonalRecorder.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPlayerBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPlayerVideo.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPopupMenu.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletRandomConnectJoin.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletRandomConnectJoinSearch.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSearchPage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceAboutMe.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceAvatarImage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceBaseSettings.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRelay.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceChatRoom.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceConnectionTest.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceHostGroup.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceHostNetwork.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRandomConnect.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRandomConnectRelay.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRelay.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceShareFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceShareWebCam.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceStoryboard.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsAboutMe.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsAvatarImage.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsChatRoom.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsConnectionTest.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsFileXfer.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostChatRoom.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostGroup.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostNetwork.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostRandomConnect.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsMessenger.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsPage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsRandomConnect.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsRandomConnectRelay.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsShareFiles.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsShareWebCam.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsStoryboard.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsTruthOrDare.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsVideoPhone.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsVoicePhone.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletShareOfferList.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletShareServicesPage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSnapshot.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletTestAndDebug.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletTheme.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletUploads.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletUserIdentity.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppTranslate.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetFaceWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetPhotoWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetTextWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetVideoWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetVoiceWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetBaseWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AvatarBar.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/BottomBarWidget.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/CamTitleBarPreview.h \	
    $$PWD/AppsSrc/GoTvCommon/QtSource/ChatRoomWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/CamLogic.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ChatEntryWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/DialogConfirmRemoveMessage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/EventsQtToGoTv.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileItemInfo.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendList.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendListDelegate.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileActionBarWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileActionMenu.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileItemWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileListReplySession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileShareItemWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileXferWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendListEntryWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendListWidget.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiConnectMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiFileActionSession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiFileXferSession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHelpers.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoin.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoinList.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoinMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoinSession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostSession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiMembershipAvailableCallback.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiMembershipAvailableMgr.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferMgrBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferClientMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferHostMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferSession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiParams.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUser.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserBase.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserMgr.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserListWidget.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoin.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoinList.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoinMgr.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoinSession.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserSessionBase.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiThumb.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiThumbList.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiThumbMgr.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/HelpBrowser.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HistoryEntryWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HistoryListWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HostJoinRequestListItem.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HostJoinRequestListWidget.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/HostListWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HostListItem.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HomeWindow.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/IdentLogicInterface.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/IdentWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImageListEntry.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImagePickBar.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImageListRow.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImageListWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InformationWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputAllWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputBaseWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputFaceWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputPhotoWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputTextWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputVideoWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputVoiceWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InstMsgWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ListWidgetBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/LogMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/LogoRenderer.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/LogWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MenuDefs.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/MenuBase.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/MenuCam.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MessengerPage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MyIcons.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MyIconsDefs.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MySndMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MultiSessionState.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/NetworkKeyWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/NetworkTestWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/NetAvailStatusWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferBarWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferSessionCallbackInterface.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferSessionLogic.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferSessionState.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PermissionWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PermissionListItem.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PersonOfferListItem.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PersonOfferListWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PluginSettingsWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlOffScreenSurface.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderKodiThread.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlLogic.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlShaders.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderLogoShaders.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderShaderQt.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/SearchParamsWidget.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ServiceSettingsWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/SessionWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ShareOfferListItem.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ShareOfferListWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/SoundCtrlWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/StoryWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioDefs.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioInIo.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioInThread.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioIoMgr.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioMixer.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioOutIo.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioOutThread.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioTestGenerator.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioUtils.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/SoundDefs.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TextChatLogic.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ThumbnailEditWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ThumbnailChooseWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ThumbnailViewWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TodGameDefs.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TodGameLogic.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TodGameWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiActivityClient.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiActivityInterface.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiFileXferClient.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiFileXferInterface.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiHardwareControlInterface.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiHardwareCtrlClient.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiOfferInterface.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiUserUpdateClient.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiUserUpdateInterface.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiThumbUpdateClient.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiThumbUpdateInterface.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserJoinListItem.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserJoinListWidget.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserListItem.h \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserListWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TitleBarWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VideoSinkGrabber.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAspectFrame.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxContextMenu.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxComboBox.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAvatarImage.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxPushButton.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxComboBoxFileFilter.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxLabel.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMyFileInfo.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxSndInstance.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxFlatButton.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxFrame.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenu.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenuButton.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenuButtonBottom.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenuButtonTop.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxProgressBar.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxResourceToRealFile.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxScrollArea.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxShredderButton.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxSpinProgress.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxTagLabel.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxTilePositioner.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VidWidget.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxWidgetBase.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAppStyle.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAppTheme.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAppDisplay.h \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxPlainTextEdit.h \
    $$PWD/GoTvAppConfig.h \
    $$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/GuiInterface/config_libgotvptop.h \
    $$PWD/GuiInterface/GoTvRenderFrame.h \
    $$PWD/GuiInterface/IAudioInterface.h \
    $$PWD/GuiInterface/IDefs.h \
    $$PWD/GuiInterface/IFromGui.h \
    $$PWD/GuiInterface/IGoTv.h \
    $$PWD/GuiInterface/IDefs.h \
    $$PWD/GuiInterface/IGoTvRender.h \
    $$PWD/GuiInterface/ILog.h \
    $$PWD/GuiInterface/IScan.h \
    $$PWD/GuiInterface/IToGui.h \
    $$PWD/GuiInterface/OsInterface/OsInterface.h \
    $$PWD/GuiInterface/OsWin32/IWin32.h \
    $$PWD/GuiInterface/OsLinux/ILinux.h \
    $$PWD/GuiInterface/OsAndroid/IAndroid.h

SOURCES += $$PWD/AppsSrc/NoLimitConnectMain/AppSource/main.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AcceptCancelWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AccountDb.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AccountMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityAddRemoveLibraryFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityAppSetup.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityBrowseFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityChooseTestWebsiteUrl.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityCreateAccount.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityDownloadItemMenu.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityFileSearch.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ActivityInformation.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityIsPortOpenTest.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityMessageBox.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityNetworkState.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityPermissions.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanPeopleSearch.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanProfiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanStoryBoards.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityScanWebCams.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivitySessionOptions.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityShowHelp.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivitySoundOptions.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityStoryBoard.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityTimedMessage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityViewLibraryFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityViewMySharedFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ActivityYesNoMsgBox.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppCommon.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppCommonAudio.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppCommonEvents.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppCommonLogin.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppCommonRender.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppDefs.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppGlobals.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppProfile.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppSettings.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppSetup.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletAboutApp.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletApplicationInfo.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletAssetPlayerBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletBase.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletBrowseFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletCamClipPlayer.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletCamSettings.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletCamTest.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChatRoomClient.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletChatRoomJoin.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChatRoomJoinSearch.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletChooseThumbnail.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientAvatarImage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientRandomConnect.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientShareFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientShareWebCam.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletClientStoryboard.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletDownloads.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletEditAboutMe.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletEditAvatarImage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletEditStoryboard.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletFriendListClient.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGalleryImage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGalleryEmoticon.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGalleryThumb.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGetStarted.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupJoin.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupJoinSearch.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupListClient.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletGroupListLocalView.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletHelpNetSignalBars.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostJoinRequestList.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostGroupStatus.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostNetworkStatus.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletHostSelect.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletInviteAccept.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletInviteCreate.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletJoinGroupStatus.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletJoinBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletKodi.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLaunchPage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLaunchWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLibrary.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLog.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLogSettings.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletLogView.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletMgr.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletMultiMessenger.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletNetHostingPage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletNetworkSettings.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletPersonOfferList.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerChangeFriendship.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerReplyFileOffer.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerSelectFileToSend.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerSessionFileOffer.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerTodGame.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerVideoPhone.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerViewSharedFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPeerVoicePhone.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPermissionList.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPersonalRecorder.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPlayerBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPlayerVideo.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletPopupMenu.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletRandomConnectJoin.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletRandomConnectJoinSearch.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSearchPage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceAboutMe.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceAvatarImage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceBaseSettings.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceChatRoom.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceConnectionTest.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceHostGroup.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceHostNetwork.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRandomConnect.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRandomConnectRelay.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceRelay.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceShareFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceShareWebCam.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletServiceStoryboard.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsAboutMe.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsAvatarImage.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsChatRoom.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsConnectionTest.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsFileXfer.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostChatRoom.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostGroup.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostNetwork.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsHostRandomConnect.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsMessenger.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsPage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsRandomConnect.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsRandomConnectRelay.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsShareFiles.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsShareWebCam.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsStoryboard.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsTruthOrDare.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsVideoPhone.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSettingsVoicePhone.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletShareOfferList.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletShareServicesPage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletSnapshot.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppletTestAndDebug.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletTheme.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletUploads.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AppletUserIdentity.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/AppTranslate.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/BottomBarWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetBaseWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetFaceWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetPhotoWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetTextWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetVideoWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AssetVoiceWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/AvatarBar.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/CamLogic.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/CamTitleBarPreview.cpp \	
    $$PWD/AppsSrc/GoTvCommon/QtSource/ChatRoomWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ChatEntryWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/DialogConfirmRemoveMessage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/EventsQtToGoTv.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileActionBarWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileActionMenu.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileItemInfo.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileItemWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileListReplySession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileShareItemWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FileXferWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendList.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendListDelegate.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendListWidget.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiConnectMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiFileActionSession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiFileXferSession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHelpers.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoin.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoinList.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoinMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostJoinSession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiHostSession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiMembershipAvailableMgr.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferMgrBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferClientMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferHostMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiOfferSession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiParams.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUser.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserBase.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoin.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoinList.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoinMgr.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserJoinSession.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserSessionBase.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiUserMgr.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiThumb.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiThumbList.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/GuiThumbMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HostJoinRequestListItem.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HostJoinRequestListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HomeWindow.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/HelpBrowser.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HistoryEntryWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HistoryListWidget.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/HostListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/HostListItem.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImageListEntry.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImagePickBar.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImageListRow.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ImageListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InformationWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputAllWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputBaseWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputFaceWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputPhotoWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputTextWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputVideoWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InputVoiceWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/IdentLogicInterface.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/IdentWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/InstMsgWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/FriendListEntryWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ListWidgetBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/LogMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/LogWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/LogoRenderer.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/MenuBase.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/MenuCam.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MessengerPage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MultiSessionState.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MyIcons.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/MySndMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/NetAvailStatusWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/NetworkKeyWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/NetworkTestWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferBarWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferSessionLogic.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/OfferSessionState.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingFileMenu.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingFileShare.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingFriend.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingNotify.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingOfferToFriend.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingScan.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingSearch.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingServers.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/P2PThingMedia.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PermissionWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PermissionListItem.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PersonOfferListItem.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PersonOfferListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/PluginSettingsWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlMatrix.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlOffScreenSurface.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlWidgetFonts.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlWidgetRender.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlWidgetTextures.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderKodiThread.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlLogic.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderShaderDefsGl.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlShaders.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderShaderQt.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderLogoShaders.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/RenderGlWidgetShaderInterface.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/SearchParamsWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/SessionWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ServiceSettingsWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ShareOfferListItem.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ShareOfferListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioInIo.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioInThread.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioIoMgr.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioMixer.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioOutIo.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioOutThread.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioTestGenerator.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/soundio/AudioUtils.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/SoundCtrlWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/StoryWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TextChatLogic.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TitleBarWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TodGameDefs.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TodGameLogic.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/TodGameWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ThumbnailEditWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ThumbnailChooseWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ThumbnailViewWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiActivityClient.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiFileXferClient.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiHardwareCtrlClient.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiUserUpdateClient.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/ToGuiThumbUpdateClient.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserJoinListItem.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserJoinListWidget.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserListItem.cpp \
	$$PWD/AppsSrc/GoTvCommon/QtSource/UserListWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VideoSinkGrabber.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAspectFrame.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxComboBox.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxContextMenu.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAvatarImage.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxFrame.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenuButton.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenuButtonBottom.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenuButtonTop.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxPushButton.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxProgressBar.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxComboBoxFileFilter.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxFlatButton.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxLabel.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMyFileInfo.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxSndInstance.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxResourceToRealFile.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxScrollArea.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxShredderButton.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxSpinProgress.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxTagLabel.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxTilePositioner.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VidWidget.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxWidgetBase.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxMenu.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAppStyle.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAppTheme.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxAppDisplay.cpp \
    $$PWD/AppsSrc/GoTvCommon/QtSource/VxPlainTextEdit.cpp \
    $$PWD/GuiInterface/GoTvRenderFrame.cpp \
	$$PWD/GuiInterface/IDefs.cpp \
    $$PWD/GuiInterface/IGoTv.cpp \
    $$PWD/GuiInterface/IGoTvFromGui.cpp \
    $$PWD/GuiInterface/IGoTvRender.cpp \
    $$PWD/GuiInterface/IGoTvToGui.cpp \
    $$PWD/GuiInterface/ILog.cpp \
    $$PWD/GuiInterface/IToGui.cpp \
    $$PWD/GuiInterface/OsInterface/OsInterface.cpp \
    $$PWD/GuiInterface/OsWin32/IWin32.cpp \
    $$PWD/GuiInterface/OsLinux/ILinux.cpp \
    $$PWD/GuiInterface/OsAndroid/IAndroid.cpp

FORMS += $$PWD/AppsSrc/GoTvCommon/Forms/ActivityAddRemoveLibraryFiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityAppSetup.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityBrowseFiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityChooseTestWebsiteUrl.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityConnectionOptions.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityCreateAccount.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityDownloadItemMenu.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityFileSearch.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityInformation.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityIsPortOpenTest.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityMessageBox.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityNetworkStartupTest.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityNetworkStatus.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityNetworkTest.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityPermissions.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityScanPeopleSearch.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityScanProfiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityScanStoryBoards.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityScanWebCams.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivitySessionOptions.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityShowHelp.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivitySoundOptions.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityStoryBoard.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityTimedMessage.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityVideoOptions.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityViewLibraryFiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityViewMySharedFiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityWebCamClient.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityYesNo.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ActivityBase.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AcceptCancelWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletAboutApp.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletApplicationInfo.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletBrowseFiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletCamClipPlayer.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletCamSettings.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletCamTest.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletChatRoomClient.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletChatRoomJoin.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletChatRoomJoinSearch.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletChooseThumbnail.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletClientRandomConnect.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletDownloads.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletEditAboutMe.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletEditAvatarImage.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletEditStoryBoard.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletFriendListClient.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGalleryImage.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGalleryEmoticon.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGalleryThumb.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGetStarted.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGoTvPtoPNetworkHost.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGroupHost.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletGroupJoin.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGroupJoinSearch.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGroupListClient.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletGroupListLocalView.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletHelpNetSignalBars.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletHostJoinRequestList.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletHostGroupStatus.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletHostNetworkStatus.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletHostSelect.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletInviteAccept.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletInviteCreate.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletJoinGroupStatus.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletKodi.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletLaunchWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletLibrary.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletLog.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletLogSettings.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletLogView.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletMultiMessenger.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletNetworkKey.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletNetworkSettings.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletPersonOfferList.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerChangeFriendship.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerReplyOfferFile.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerSelectFileToSend.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerSessionFileOffer.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerTodGame.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerVideoPhone.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerViewSharedFiles.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPeerVoicePhone.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPermissionList.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPersonalRecorder.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPlayerVideo.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletPopupMenu.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletRandomConnectJoin.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletRandomConnectJoinSearch.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletServiceBase.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletServiceBaseSettings.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletServiceChatRoom.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletSettingsHostChatRoom.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletSettingsHostGroup.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletSettingsHostNetwork.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletSharedContent.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletShareOfferList.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletSnapshot.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/AppletTestAndDebug.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletTheme.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletUploads.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AppletUserIdentity.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AssetFaceWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AssetPhotoWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AssetTextWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AssetVideoWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AssetVoiceWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/AvatarBarWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/BottomBarWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/CentralFrame.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/CentralWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ChatEntryWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ChatRoomWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/DialogConfirmRemoveMessage.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FileActionBarWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FileActionMenu.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FileDisplayWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FileItemWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FileShareItemWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FileXferWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/FriendListDlg.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/GuiUserListEntryWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/HostJoinRequestListItem.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/HistoryEntryWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/HomeWindow.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/HostListItem.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/IdentWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ImageListEntry.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ImageListRow.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ImageListWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ImagePickBar.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InformationWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InputAllWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InputFaceWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InputPhotoWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InputTextWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InputVideoWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InputVoiceWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/InstMsgWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/LogWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/NetworkKeyWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/NetworkTestWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/OfferBarWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/PermissionWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/PermissionListItemWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/PersonOfferListItem.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/PluginSettingsWidget.ui \
	$$PWD/AppsSrc/GoTvCommon/Forms/SearchParamsWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ServiceSettingsWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/SessionWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ShareOfferListItem.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/SoundCtrlWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/StoryWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ThumbnailEditWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/ThumbnailChooseWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/TitleBarWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/TodGameWidget.ui \
    $$PWD/AppsSrc/GoTvCommon/Forms/VidWidget.ui





