INCLUDEPATH += $$PWD/DependLibs
INCLUDEPATH += $$PWD/kodi_src/xbmc/xbmc

HEADERS += 	$$PWD/DependLibs/PktLib/AllPkts.h \
    $$PWD/DependLibs/PktLib/MatchParams.h \
    $$PWD/DependLibs/PktLib/PktAnnList.h \
    $$PWD/DependLibs/PktLib/PktAnnounce.h \
	$$PWD/DependLibs/PktLib/PktBlobEntry.h \
    $$PWD/DependLibs/PktLib/PktChatReq.h \
    $$PWD/DependLibs/PktLib/PktDebugHelpers.h \
    $$PWD/DependLibs/PktLib/PktHostAnnounce.h \
	$$PWD/DependLibs/PktLib/PktsHostSearch.h \
    $$PWD/DependLibs/PktLib/PktLogReply.h \
    $$PWD/DependLibs/PktLib/PktLogReq.h \
    $$PWD/DependLibs/PktLib/PktPluginHandlerBase.h \
	$$PWD/DependLibs/PktLib/PktsOfferXfer.h \
	$$PWD/DependLibs/PktLib/PktsPing.h \
	$$PWD/DependLibs/PktLib/PktsPluginOffer.h \
	$$PWD/DependLibs/PktLib/PktsPluginSetting.h \
    $$PWD/DependLibs/PktLib/PktRequestErrors.h \
    $$PWD/DependLibs/PktLib/PktSysHandlerBase.h \
    $$PWD/DependLibs/PktLib/PktTcpPunch.h \
    $$PWD/DependLibs/PktLib/PktTypes.h \
    $$PWD/DependLibs/PktLib/PktVoiceReply.h \
    $$PWD/DependLibs/PktLib/PktVoiceReq.h \
    $$PWD/DependLibs/PktLib/PktsAssetXfer.h \
	$$PWD/DependLibs/PktLib/PktsBaseXfer.h \
	$$PWD/DependLibs/PktLib/PktsBlobXfer.h \
    $$PWD/DependLibs/PktLib/PktsFileList.h \
    $$PWD/DependLibs/PktLib/PktsFileShare.h \
	$$PWD/DependLibs/PktLib/PktsFriendOffer.h \
	$$PWD/DependLibs/PktLib/PktsHostJoin.h \
    $$PWD/DependLibs/PktLib/PktsImAlive.h \
    $$PWD/DependLibs/PktLib/PktsMembership.h \
    $$PWD/DependLibs/PktLib/PktsMultiSession.h \
    $$PWD/DependLibs/PktLib/PktsPing.h \
    $$PWD/DependLibs/PktLib/PktsPluginOffer.h \
    $$PWD/DependLibs/PktLib/PktsPluginSetting.h \
    $$PWD/DependLibs/PktLib/PktsPushToTalk.h \
    $$PWD/DependLibs/PktLib/PktsRelay.h \
	$$PWD/DependLibs/PktLib/PktsScan.h \
	$$PWD/DependLibs/PktLib/PktsSearch.h \
    $$PWD/DependLibs/PktLib/PktsSession.h \
    $$PWD/DependLibs/PktLib/PktsStoryBoard.h \
	$$PWD/DependLibs/PktLib/PktsThumbXfer.h \
    $$PWD/DependLibs/PktLib/PktsTodGame.h \
    $$PWD/DependLibs/PktLib/PktsVideoFeed.h \
    $$PWD/DependLibs/PktLib/PktsWebServer.h \
	$$PWD/DependLibs/PktLib/PluginId.h \
	$$PWD/DependLibs/PktLib/PluginIdList.h \
	$$PWD/DependLibs/PktLib/SearchParams.h \
    $$PWD/DependLibs/PktLib/VxCommon.h \
    $$PWD/DependLibs/PktLib/VxConnectId.h \
    $$PWD/DependLibs/PktLib/VxConnectInfo.h \
    $$PWD/DependLibs/PktLib/VxFriendMatch.h \
    $$PWD/DependLibs/PktLib/VxNetIdentBase.h \
    $$PWD/DependLibs/PktLib/VxOnlineStatusFlags.h \
    $$PWD/DependLibs/PktLib/VxPktHdr.h \
    $$PWD/DependLibs/PktLib/VxRelayFlags.h \
    $$PWD/DependLibs/PktLib/VxSearchDefs.h \
    $$PWD/DependLibs/PktLib/VxSearchFlags.h

SOURCES += 	$$PWD/DependLibs/PktLib/MatchParams.cpp \
	$$PWD/DependLibs/PktLib/PktAnnList.cpp \
    $$PWD/DependLibs/PktLib/PktAnnounce.cpp \
	$$PWD/DependLibs/PktLib/PktBlobEntry.cpp \
    $$PWD/DependLibs/PktLib/PktChatReq.cpp \
    $$PWD/DependLibs/PktLib/PktDebugHelpers.cpp \
    $$PWD/DependLibs/PktLib/PktHostAnnounce.cpp \
	$$PWD/DependLibs/PktLib/PktsHostSearch.cpp \
    $$PWD/DependLibs/PktLib/PktLogReply.cpp \
    $$PWD/DependLibs/PktLib/PktLogReq.cpp \
	$$PWD/DependLibs/PktLib/PktsOfferXfer.cpp \
    $$PWD/DependLibs/PktLib/PktPluginHandlerBase.cpp \
    $$PWD/DependLibs/PktLib/PktSysHandlerBase.cpp \
    $$PWD/DependLibs/PktLib/PktTcpPunch.cpp \
    $$PWD/DependLibs/PktLib/PktVoiceReply.cpp \
    $$PWD/DependLibs/PktLib/PktVoiceReq.cpp \
    $$PWD/DependLibs/PktLib/PktsAssetXfer.cpp \
    $$PWD/DependLibs/PktLib/PktsBaseXfer.cpp \
	$$PWD/DependLibs/PktLib/PktsBlobXfer.cpp \
    $$PWD/DependLibs/PktLib/PktsFileList.cpp \
    $$PWD/DependLibs/PktLib/PktsFileShare.cpp \
	$$PWD/DependLibs/PktLib/PktsFriendOffer.cpp \
	$$PWD/DependLibs/PktLib/PktsHostJoin.cpp \
    $$PWD/DependLibs/PktLib/PktsImAlive.cpp \
    $$PWD/DependLibs/PktLib/PktsMembership.cpp \
    $$PWD/DependLibs/PktLib/PktsMultiSession.cpp \
    $$PWD/DependLibs/PktLib/PktsPing.cpp \
    $$PWD/DependLibs/PktLib/PktsPluginOffer.cpp \
    $$PWD/DependLibs/PktLib/PktsPluginSetting.cpp \
    $$PWD/DependLibs/PktLib/PktsPushToTalk.cpp \
    $$PWD/DependLibs/PktLib/PktsRelay.cpp \
	$$PWD/DependLibs/PktLib/PktsScan.cpp \
	$$PWD/DependLibs/PktLib/PktsSearch.cpp \
    $$PWD/DependLibs/PktLib/PktsSession.cpp \
    $$PWD/DependLibs/PktLib/PktsStoryBoard.cpp \
    $$PWD/DependLibs/PktLib/PktsThumbXfer.cpp \
    $$PWD/DependLibs/PktLib/PktsTodGame.cpp \
    $$PWD/DependLibs/PktLib/PktsVideoFeed.cpp \
    $$PWD/DependLibs/PktLib/PktsWebServer.cpp \
	$$PWD/DependLibs/PktLib/PluginId.cpp \
	$$PWD/DependLibs/PktLib/PluginIdList.cpp \
	$$PWD/DependLibs/PktLib/SearchParams.cpp \
    $$PWD/DependLibs/PktLib/VxCommon.cpp \
    $$PWD/DependLibs/PktLib/VxConnectId.cpp \
    $$PWD/DependLibs/PktLib/VxConnectInfo.cpp \
    $$PWD/DependLibs/PktLib/VxFriendMatch.cpp \
    $$PWD/DependLibs/PktLib/VxNetIdentBase.cpp \
    $$PWD/DependLibs/PktLib/VxOnlineStatusFlags.cpp \
    $$PWD/DependLibs/PktLib/VxPktHdr.cpp \
    $$PWD/DependLibs/PktLib/VxRelayFlags.cpp \
    $$PWD/DependLibs/PktLib/VxSearchFlags.cpp

