
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p/include

win32{
    INCLUDEPATH += $$PWD/sysheaders
}

unix{
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p/include
}

INCLUDEPATH += $$PWD/kodi_src/xbmc/xbmc/
INCLUDEPATH += $$PWD/DependLibs/



HEADERS += 	$$PWD/AppCompilerConfig.h \
    $$PWD/AppCpuArchDefines.h \
    $$PWD/AppDependLibrariesConfig.h \
    $$PWD/GuiInterface/IDefs.h \
    $$PWD/GuiInterface/IFromGui.h \
    $$PWD/GuiInterface/IGoTv.h \
    $$PWD/GuiInterface/ILog.h \
    $$PWD/GuiInterface/IScan.h \
    $$PWD/GuiInterface/IToGui.h \
    $$PWD/GuiInterface/config_libgotvptop.h \
    $$PWD/AppTargetOsConfig.h \
	$$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseInfo.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseMgr.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferSession.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetInfo.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetMgr.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferSession.h \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseHostInfo.h \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseJoinInfo.h \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseInfo.h \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseSessionInfo.h \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigList.h \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListDb.h \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListInfo.h \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListLib.h \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobInfo.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobMgr.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobXferSession.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectedInfo.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectedListAll.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectedListBase.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectionMgr.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectReqInfo.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/HandshakeInfo.h \
	$$PWD/ptop_src/ptop_engine_src/Connections/HandshakeList.h \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectInfo.h \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectMgr.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/WebRtcTypeDefs.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_common.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_core.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_core_internal.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_logging.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_logging_file_handling.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_rdft.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_resampler.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/array_view.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/arraysize.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/atomic32.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/atomicops.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device_buffer.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device_config.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device_defines.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device_generic.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_processing.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_util.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/base64.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/basictypes.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/block_mean_calculator.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/byteorder.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/checks.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/common_types.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/constructormagic.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/cpu_features_wrapper.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/critical_section_wrapper.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/criticalsection.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/delay_estimator.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/delay_estimator_internal.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/delay_estimator_wrapper.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/echo_cancellation.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/echo_cancellation_internal.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/echo_common.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event_timer_posix.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event_timer_win.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event_wrapper.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/fake_audio_device.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/fileutils.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/fine_audio_buffer.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/format_macros.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/logging.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/module.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/module_common_types.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/pathutils.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/platform_file.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/platform_thread.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/platform_thread_types.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/random.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/real_fft.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/ring_buffer.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/safe_conversions.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/safe_conversions_impl.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/scoped_ptr.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/scoped_ref_ptr.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/scopedptrcollection.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/sec_buffer.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/signal_processing_library.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/spl_inl.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/spl_inl_armv7.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/spl_inl_mips.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/stringencode.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/stringutils.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/template_util.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/thread_annotations.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/thread_checker.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/thread_checker_impl.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/tick_util.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/timeutils.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/urlencode.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/wav_file.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/wav_header.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/win32.h \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/win32filesystem.h \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinCallbackInterface.h \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinInfo.h \
    $$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinedLastDb.h \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinInfoDb.h \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinMgr.h \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieListCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieInfo.h \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieListDb.h \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedListCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedInfo.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedListDb.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostUrlInfo.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostUrlListDb.h \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostUrlListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/DirectConnectListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/FriendListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/IdentListCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/IdentListMgrBase.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/IgnoreListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/NearbyListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/OnlineListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/AudioUtil.h \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/EchoCancel.h \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/MediaClient.h \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/MediaProcessor.h \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/RawAudio.h \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/RawVideo.h \
    $$PWD/ptop_src/ptop_engine_src/Membership/Membership.h \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipAvailableMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipAvailableCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipHostedMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipHostedListCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipMgrBase.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetActionBase.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetActionIdle.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetActionIsMyPortOpen.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetServiceDefs.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetServiceHdr.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetServiceUtils.h \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetServicesMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Network/ConnectRequest.h \
    $$PWD/ptop_src/ptop_engine_src/Network/DirectConnectTester.h \
    $$PWD/ptop_src/ptop_engine_src/Network/Firewall.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NearbyMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetConnector.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetPortForward.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkDefs.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkEventAvail.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkEventBase.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkEventLost.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateAvail.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateBase.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateLost.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateMachine.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateOnlineDirect.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateOnlineThroughRelay.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateTestConnection.h \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateWaitForRelay.h \
    $$PWD/ptop_src/ptop_engine_src/Network/RcMulticast.h \
    $$PWD/ptop_src/ptop_engine_src/NetworkMonitor/NetworkMonitor.h \
    $$PWD/ptop_src/ptop_engine_src/NetworkMonitor/NetStatusAccum.h \
	$$PWD/ptop_src/ptop_engine_src/NetworkTest/IsPortOpenTest.h \
    $$PWD/ptop_src/ptop_engine_src/NetworkTest/NetworkTestBase.h \
    $$PWD/ptop_src/ptop_engine_src/NetworkTest/PingResponseServer.h \
    $$PWD/ptop_src/ptop_engine_src/NetworkTest/RunUrlAction.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseInfo.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseMgr.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseXferSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientInfo.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientMgr.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientXferSession.h \
	$$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostInfo.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostMgr.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostXferSession.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/BrowserHttpConnection.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/ContactList.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/EngineParams.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/EngineSettings.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/EngineSettingsDefaultValues.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/FileShareSettings.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PConnectList.h \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngine.h \
	$$PWD/ptop_src/ptop_engine_src/P2PEngine/VxSktLoopback.h \
    $$PWD/ptop_src/ptop_engine_src/PluginSettings/PluginSetting.h \
    $$PWD/ptop_src/ptop_engine_src/PluginSettings/PluginSettingDb.h \
    $$PWD/ptop_src/ptop_engine_src/PluginSettings/PluginSettingMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/AudioJitterBuffer.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileLibraryDb.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileLibraryMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileRxSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileShareXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileShareXferSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileToXfer.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileTxSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileXferBaseMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileXferMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileXferPluginSession.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostBaseMgr.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostClientMgr.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostClientSearchMgr.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostSearchEntry.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostServerMgr.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostServerSearchMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/LibraryFileInfo.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/P2PSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBase.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseFileXfer.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseHostClient.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseHostService.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseMultimedia.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseRelay.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseService.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseWebServer.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginChatRoomClient.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginChatRoomHost.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginPeerUserClient.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginConnectionTestClient.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginConnectionTestHost.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginGroupClient.h \	
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginGroupHost.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginNetworkHost.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginNetworkSearchList.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginRandomConnectClient.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginRandomConnectHost.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginFileXfer.h \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginPeerUserHost.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginInvalid.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginMessenger.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginNetServices.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginPushToTalk.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceAboutMe.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginConnectionTestHost.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceFileShare.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceRelay.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceStoryboard.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceWebCam.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginSessionBase.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginSessionMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginTruthOrDare.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginVideoPhone.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginVoicePhone.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PushToTalkFeedMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RcWebProxy.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/Relay.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelayClientSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelayClientTestSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelayServerSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelayServerTestSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelaySession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RxSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SessionMgrBase.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFileInfo.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFilesDb.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFilesFinder.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFilesMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/TodGameSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/TxSession.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/VideoFeedMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Plugins/VoiceFeedMgr.h \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScan.h \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScanAction.h \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScanMatchedConnection.h \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScanPic.h \
    $$PWD/ptop_src/ptop_engine_src/SktLists/SktListCallbackInterface.h \
    $$PWD/ptop_src/ptop_engine_src/SktLists/SktListMgr.h \
    $$PWD/ptop_src/ptop_engine_src/SktLists/SktListMgrBase.h \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbCallbackInterface.h \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbInfo.h \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbInfoDb.h \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbMgr.h \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbRxSession.h \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbTxSession.h \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferDb.h \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferMgr.h \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferSession.h \
    $$PWD/ptop_src/ptop_engine_src/UrlMgr/UrlMgr.h \
	$$PWD/ptop_src/ptop_engine_src/User/User.h \
	$$PWD/ptop_src/ptop_engine_src/User/UserList.h \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinCallbackInterface.h \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinInfo.h \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinInfoDb.h \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinMgr.h \
	$$PWD/ptop_src/ptop_engine_src/UserOnlineMgr/UserOnlineCallbackInterface.h \
	$$PWD/ptop_src/ptop_engine_src/UserOnlineMgr/UserOnlineMgr.h \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebPageBuilder.h \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebPageSettings.h \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebServer.h \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebServerLib.h \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebSkt.h


SOURCES += \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseTxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferPktCreate.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetBase/AssetBaseXferSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetTxSession.cpp \
	$$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferPktCreate.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/AssetMgr/AssetXferSession.cpp \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseHostInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseJoinInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/BaseInfo/BaseSessionInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigList.cpp \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/BigListLib/BigListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobTxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/BlobXferMgr/BlobXferSession.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectedInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectedListAll.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectedListBase.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectionMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/ConnectReqInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/HandshakeInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/Connections/HandshakeList.cpp \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/ConnectMgr/ConnectMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_core.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_core_mips.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_core_neon.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_core_sse2.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_logging_file_handling.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_rdft.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_rdft_mips.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_rdft_neon.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_rdft_sse2.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/aec_resampler.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/atomic32_posix.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/atomic32_win.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device_buffer.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_device_generic.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/audio_util.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/base64.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/block_mean_calculator.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/checks.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/common_types.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/cpu_features.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/cpu_features_android.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/cpu_features_linux.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/criticalsection.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/delay_estimator.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/delay_estimator_wrapper.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/echo_cancellation.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event_timer_posix.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event_timer_win.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/event_wrapper.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/fileutils.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/fine_audio_buffer.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/logging.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/pathutils.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/platform_file.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/platform_thread.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/random.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/randomization_functions.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/ring_buffer.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/stringencode.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/stringutils.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/thread_checker_impl.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/tick_util.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/timeutils.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/urlencode.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/wav_file.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/wav_header.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/win32.cpp \
    $$PWD/ptop_src/ptop_engine_src/EchoCancel/win32filesystem.cpp \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinedLastDb.cpp \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinInfoDb.cpp \
	$$PWD/ptop_src/ptop_engine_src/HostJoinMgr/HostJoinMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieListDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/GroupieListMgr/GroupieListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedListDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostedListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostUrlInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostUrlListDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/HostListMgr/HostUrlListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/DirectConnectListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/FriendListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/IdentListMgrBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/IgnoreListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/NearbyListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/IdentListMgrs/OnlineListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/AudioUtil.cpp \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/EchoCancel.cpp \
    $$PWD/ptop_src/ptop_engine_src/MediaProcessor/MediaProcessor.cpp \
    $$PWD/ptop_src/ptop_engine_src/Membership/Membership.cpp \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipAvailableMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipHostedMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Membership/MembershipMgrBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetActionBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetActionIdle.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetActionIsMyPortOpen.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetServiceUtils.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetServices/NetServicesMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/ConnectRequest.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/DirectConnectTester.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/Firewall.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NearbyMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetConnector.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetPortForward.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkEventAvail.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkEventBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkEventLost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateAvail.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateLost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateMachine.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateOnlineDirect.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateOnlineThroughRelay.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateTestConnection.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/NetworkStateWaitForRelay.cpp \
    $$PWD/ptop_src/ptop_engine_src/Network/RcMulticast.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetworkMonitor/NetStatusAccum.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetworkMonitor/NetworkMonitor.cpp \
	$$PWD/ptop_src/ptop_engine_src/NetworkTest/IsPortOpenTest.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetworkTest/NetworkTestBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetworkTest/PingResponseServer.cpp \
    $$PWD/ptop_src/ptop_engine_src/NetworkTest/RunUrlAction.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseTxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferBase/OfferBaseXferSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientTxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferClientMgr/OfferClientXferSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostTxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/OfferHostMgr/OfferHostXferSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/BrowserHttpConnection.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/ContactList.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/EngineParams.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/EngineSettings.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/FileShareSettings.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PConnectList.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngine.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineAssetMgrCallbacks.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineConnect.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineConnections.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineContact.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineFromGui.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineHostList.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineIgnoredAndHackers.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineMediaProcessorCallbacks.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEnginePktAnnChanged.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEnginePktHandlers.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineRelay.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineScan.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineSearch.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineSktCallback.cpp \
    $$PWD/ptop_src/ptop_engine_src/P2PEngine/P2PEngineTimerThread.cpp \
	$$PWD/ptop_src/ptop_engine_src/P2PEngine/VxSktLoopback.cpp \
	$$PWD/ptop_src/ptop_engine_src/PluginSettings/PluginSetting.cpp \
	$$PWD/ptop_src/ptop_engine_src/PluginSettings/PluginSettingDb.cpp \
	$$PWD/ptop_src/ptop_engine_src/PluginSettings/PluginSettingMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/AudioJitterBuffer.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileLibraryDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileLibraryMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileRxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileShareXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileShareXferSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileToXfer.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileTxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileXferBaseMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileXferMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/FileXferPluginSession.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostBaseMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostClientMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostClientSearchMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostSearchEntry.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostServerMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/HostServerSearchMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/LibraryFileInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/P2PSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseFileXfer.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseFileXferPktHandlers.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseHostClient.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseHostService.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseMultimedia.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginBasePktHandlers.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseRelay.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseRelayPktHandlers.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseRelayTests.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseService.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseWebServer.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseWebServerFiles.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginBaseWebServerPktHandlers.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginChatRoomClient.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginChatRoomHost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginPeerUserClient.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginConnectionTestClient.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginConnectionTestHost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginFileXfer.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginInvalid.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginGroupClient.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginGroupHost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginPeerUserHost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginMgrSktApi.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginMessenger.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginNetServices.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginNetworkHost.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginNetworkSearchList.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginPushToTalk.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginRandomConnectClient.cpp \
	$$PWD/ptop_src/ptop_engine_src/Plugins/PluginRandomConnectHost.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceAboutMe.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceFileShare.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceRelay.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceStoryboard.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginServiceWebCam.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginSessionBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginSessionMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginTruthOrDare.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginVideoPhone.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PluginVoicePhone.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/PushToTalkFeedMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RcWebProxy.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/Relay.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelayClientSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelayServerSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RelaySession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/RxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SessionMgrBase.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFileInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFilesDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFilesFinder.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/SharedFilesMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/TodGameSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/TxSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/VideoFeedMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Plugins/VoiceFeedMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScan.cpp \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScanAction.cpp \
    $$PWD/ptop_src/ptop_engine_src/Search/RcScanMatchedConnection.cpp \
    $$PWD/ptop_src/ptop_engine_src/SktLists/SktListMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/SktLists/SktListMgrBase.cpp \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbInfo.cpp \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbInfoDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbRxSession.cpp \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbTxSession.cpp \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferDb.cpp \
    $$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferPktCreate.cpp \
	$$PWD/ptop_src/ptop_engine_src/ThumbMgr/ThumbXferSession.cpp \
    $$PWD/ptop_src/ptop_engine_src/UrlMgr/UrlMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/User/User.cpp \
	$$PWD/ptop_src/ptop_engine_src/User/UserList.cpp \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinInfo.cpp \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinInfoDb.cpp \
	$$PWD/ptop_src/ptop_engine_src/UserJoinMgr/UserJoinMgr.cpp \
	$$PWD/ptop_src/ptop_engine_src/UserOnlineMgr/UserOnlineMgr.cpp \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebPageBuilder.cpp \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebPageSettings.cpp \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebServer.cpp \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebServerHttp.cpp \
    $$PWD/ptop_src/ptop_engine_src/WebServer/RcWebSkt.cpp

