

message(STATUS "HOST OS           : ${CMAKE_HOST_SYSTEM}")
message(STATUS "Source directory  : ${CMAKE_SOURCE_DIR}")
message(STATUS "Build directory   : ${CMAKE_BINARY_DIR}")
message(STATUS "Project           : ${PROJECT_NAME}")
message(STATUS "Project version   : ${${PROJECT_NAME}_VERSION}")
message(STATUS "Build type        : ${CMAKE_BUILD_TYPE}")
message(STATUS "Shared libs       : ${BUILD_SHARED_LIBS}")
message(STATUS "OS                : ${OS_FULL}")
message(STATUS "Platform          : ${PLATFORM}")
message(STATUS "Compiler          : ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "Cmake Bin Dir     : ${CMAKE_BINARY_DIR}")
message(STATUS "Out Bin Dir       : ${BIN_DIR}")
message(STATUS "Run Dir           : ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")

if(TARGET_OS_WINDOWS)
    message(STATUS "TARGET OS PLATFORM IS WINDOWS")
elseif(TARGET_OS_ANDROID)
    message(STATUS "TARGET OS PLATFORM IS ANDROID")
elseif(TARGET_OS_LINUX)
    message(STATUS "TARGET OS PLATFORM IS LINUX")
else()
    message(STATUS "*** ERROR NO OS PLATFORM HAS BEEN DEFINED")
endif(TARGET_OS_WINDOWS)
